## Get Info about sessions
GET http://localhost:8080/user/sessions/
Access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQG1haWwuY29tIiwibmJmIjoiMjAyMy0wNi0xMlQxMjoxMzo1MS4yNjYwOTk1WiIsInR5cGUiOiJhY2Nlc3MiLCJ1dWlkIjoiZjFkNTFjZTctZjYxYS00MTU2LTk3OWQtYTdiNzFiMzQxZjhlIn0.GXg7Q9J0bUiH6hJbhFlUQVIxMuXJAzdrahsSfcqHvFQ

###

## Get Info by Nickname
GET http://localhost:8080/user/hidden-haze

###
## Change Bio
POST http://localhost:8080/user/change/bio
content-type: application/json
Access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQG1haWwuY29tIiwibmJmIjoiMjAyMy0wNi0xMlQxMToxMTo1OC44NjY5MzA3WiIsInR5cGUiOiJhY2Nlc3MiLCJ1dWlkIjoiZjFkNTFjZTctZjYxYS00MTU2LTk3OWQtYTdiNzFiMzQxZjhlIn0.tdwiliElHAUEY9YgDO5Z4Y3s0JoJ8CRX1ae1KDzK5Jo

{
  "new_bio": "checkOut new bio"
}

###

## Change Password
POST http://localhost:8080/user/change/password
content-type: application/json
Access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQG1haWwuY29tIiwibmJmIjoiMjAyMy0wNi0xMlQxMjoxMzo1MS4yNjYwOTk1WiIsInR5cGUiOiJhY2Nlc3MiLCJ1dWlkIjoiZjFkNTFjZTctZjYxYS00MTU2LTk3OWQtYTdiNzFiMzQxZjhlIn0.GXg7Q9J0bUiH6hJbhFlUQVIxMuXJAzdrahsSfcqHvFQ

{
  "old_password": "NEwtestTPass411*",
  "new_password": "testTPass1331*",
  "new_password_again": "testTPass1331*"

}

###

## User Is Blocked
POST http://localhost:8080/user/is_user_blocked
content-type: application/json

{
  "client_id": 1
}

###

## GetUserByAccessToken
GET http://localhost:8080/user/me/info
Access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQyQG1haWwuY29tIiwibmJmIjoiMjAyMy0wNi0xMVQyMDoxMzoxNi4zMTQwMTg0WiIsInR5cGUiOiJhY2Nlc3MiLCJ1dWlkIjoiNmIxZGY2NjMtM2E0OS00YzQxLWI1OWEtN2JhOGExZjcwMjNjIn0.R3XRXQ5ZJ35WuGXlSzlfwD2hSy5VZ6DJ6sv7BhG4kYU


###
## GetUserById
GET http://localhost:8080/user/service/by_id/2
content-type: application/json

###
## GetUserByNickName
GET http://localhost:8080/user/testUser
content-type: application/json

###
GET http://localhost:8080/user/service/get_client_nickname/2
content-type: application/json

###

## Sign_UP for SSO
POST http://localhost:8080/user/sign_up
content-type: application/json
UA: t1

{
  "ip": "142.1.2.3",
  "email": "t1@mail.com",
  "password": "tesTPass114*",
  "phone": "+9999999999"
}

###
## Sign_In from SSO
POST http://localhost:8080/user/sign_in
content-type: application/json
UA: t1

{
  "email": "t1@mail.com",
  "password": "testTPass1331*",
  "ip": "124.1.2.3"
}

###
## Logout
GET http://localhost:8080/user/logout
content-type: application/json
UA: t1
Access: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InQxQG1haWwuY29tIiwibmJmIjoiMjAyMy0wNi0xMlQxMToyMzo0MC44NzAyNjM4WiIsInR5cGUiOiJhY2Nlc3MiLCJ1dWlkIjoiZjFkNTFjZTctZjYxYS00MTU2LTk3OWQtYTdiNzFiMzQxZjhlIn0.wzTMtLzxVJOkbIvX2KWZsX9Du9dYEUBN_yZ-TcWDtVM

###